version: "3.7"

services:
  test:
    image: ezconda-test
    build:
      context: ./
      dockerfile: Dockerfile
    
    container_name: ezconda-test
  
  dev:
    image: ezconda-dev
    build:
      context: ./
      dockerfile: Dockerfile.dev
    
    container_name: ezconda-dev