site_name: EZconda
site_url: https://ezconda.sarthakjariwala.com/
site_description: Environment and related file management for conda.
site_author: Sarthak Jariwala

copyright: Copyright &copy; 2021 Sarthak Jariwala

repo_url: https://github.com/SarthakJariwala/ezconda
repo_name: SarthakJariwala/ezconda
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: black
    accent: amber
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra:
  version:
    provider: mike
  # analytics:
  #   provider: plausible

nav:
  - Home : "index.md"
  - Installation : "installation.md"
  - User Guide:
    - Create new environment : "user_guide/create_new_env.md"
    - Install packages : "user_guide/install_packages.md"
    - Remove packages : "user_guide/remove_packages.md"
    - Reproducible environment : "user_guide/recreate_env.md"
    - Autocomplete commands : "user_guide/autocomplete.md"
  - Release Notes : "release_notes.md"
  - License : "license.md"

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      uess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JariwalaSarthak
    - icon: fontawesome/brands/github
      link: https://github.com/SarthakJariwala

extra_css:
  - 'css/termynal.css'
  - 'css/custom.css'

extra_javascript:
  - 'js/termynal.js'
  - 'js/custom.js'
