site_name: EZconda
site_url: https://ezconda.sarthakjariwala.com/
site_description: Environment and related file management for conda.
site_author: Sarthak Jariwala

copyright: Copyright &copy; 2021 Sarthak Jariwala

repo_url: https://github.com/SarthakJariwala/ezconda
repo_name: SarthakJariwala/ezconda
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: black
    accent: amber
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - search.suggest
    - search.highlight
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra:
  version:
    provider: mike
  # analytics:
  #   provider: plausible

nav:
  - Home : "index.md"
  - Features:
    - Create new environment : "features/create_new_env.md"
    - Install packages : "features/install_packages.md"
  - License : "license.md"

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      uess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  - pymdownx.tabbed

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JariwalaSarthak
    - icon: fontawesome/brands/github
      link: https://github.com/SarthakJariwala

extra_css:
  - 'css/termynal.css'
  - 'css/custom.css'

extra_javascript:
  - 'js/termynal.js'
  - 'js/custom.js'
