site_name: EZconda
site_url: https://ezconda.sarthakjariwala.com/
site_description: Environment and related file management for conda.
site_author: Sarthak Jariwala

copyright: Copyright &copy; 2021 Sarthak Jariwala

repo_url: https://github.com/SarthakJariwala/ezconda
repo_name: SarthakJariwala/ezconda
edit_uri: edit/main/docs/

theme:
  name: material
  custom_dir: overrides
  palette:
    scheme: default
    primary: white
    accent: amber
  logo: logo_small.png
  icon:
    repo: fontawesome/brands/github-alt
  features:
    - search.suggest
    - search.highlight
    - content.code.annotate
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - search

extra:
  version:
    provider: mike
  # analytics:
  #   provider: plausible

nav:
  - Home : "index.md"
  - User Guide:
    - Overview:
      - Introduction : "design_decisions/intro.md"
      - Specifications file : "design_decisions/specfile.md"
      - Lock file : "design_decisions/lockfile.md"
      - Reproducible environments : "design_decisions/reproducible_environments.md"
    - Create New Environment:
      - From scratch : "user_guide/create_new_env.md"
      - Using specfications file : "user_guide/create_new_env_from_specfile.md"
      - Using lock file : "user_guide/create_new_env_from_lockfile.md"
    - Install & Remove Packages:
      - Install packages : "user_guide/install_packages.md"
      - Remove packages : "user_guide/remove_packages.md"
    - Syncing Environment:
      - Sync local environment : "user_guide/sync_env.md"
    - Update Packages & Environment:
      - Update complete environment : "user_guide/update_environment.md"
    - Lock Environment:
      - Lock file for any environment : "user_guide/lock_existing_env.md"
    - Solvers:
      - Use different solver: "user_guide/changing_solvers.md"
    - Transaction & Revision Summaries:
      - Environment summary: "user_guide/summary.md"
    - Settings and Configurations:
      - Configurations : "user_guide/configuration.md"
      - Autocompletions : "user_guide/autocomplete.md"
  - Release Notes : "release_notes.md"
  - License : "license.md"

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      uess_lang: true
  - admonition
  - codehilite
  - extra
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.keys
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/JariwalaSarthak
    - icon: fontawesome/brands/github
      link: https://github.com/SarthakJariwala

extra_css:
  - 'css/termynal.css'
  - 'css/custom.css'

extra_javascript:
  - 'js/termynal.js'
  - 'js/custom.js'
