name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    
    steps:
    - uses: actions/checkout@v2.3.4
    
    - uses: s-weigand/setup-conda@v1
    
    - run: |
        conda install -c conda-forge pip typer PyYaml pytest pytest-cov codecov coverage rich
        pip install . --no-deps
    
    - name: Run Tests
      run: |
        pytest --cov=ezconda
        coverage xml
        codecov