name: Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Create 'shared' directory
      run: mkdir shared
    
    - uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          tags: test-ezconda:latest
          push: false

    - uses: addnab/docker-run-action@v3
      with:
        image: test-ezconda:latest
        options: -v "$PWD/shared:/shared"
        run: mv coverage.txt shared
    
    - name: Download Code Coverage Uploader
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov
