name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
  steps:
      - uses: actions/checkout@v2.3.4
#       - uses: docker/build-push-action@v2
#         with:
#             context: ./
#             file: ./Dockerfile
#             tags: test-ezconda:latest
#             push: false

#       - uses: addnab/docker-run-action@v3
#         with:
#           image: test-ezconda:latest
          options: -t -i 
