name: Windows Tests

on:
  - push
  - pull_request

jobs:
  tests:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2.3.4

    - uses: s-weigand/setup-conda@v1
      with:
        update-conda: true
        conda-channels: anaconda, conda-forge
    - name: Install Packages and Run Tests
      run: |
        conda install -c conda-forge mamba pip typer PyYaml pytest pytest-cov codecov coverage rich tomlkit importlib_metadata
        pip install . --no-deps
        pytest --cov=ezconda
        coverage xml
        codecov
